# Generated by Django 4.1.3 on 2023-02-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1_backend", "0002_alter_examimage_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="examimage",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
